<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nl_auth"
 *
 * Auto generated by Extension Builder 2018-12-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Auth',
    'description' => 'TYPO3 authentication, registration, profile by netzlabor-coding.de ',
    'category' => 'plugin',
    'author' => 'Maksym',
    'author_email' => 'maksim.chubin@netzlabor-coding.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [],
        'conflicts' => [],
        'suggests' => [],
    ],
];
